/* eslint-disable @typescript-eslint/no-explicit-any, prefer-const */
"use client";

import { useEffect, useState } from "react";

type View = "home"|"checkup"|"result"|"dashboard"|"copilot"|"history"|"about";
type Profile = {id?:number; company_name:string; location:string; industry:string; employee_count:string; revenue_range:string; profit_margin:string; R:number; A:number; P:number; health_score:number; constraint_score:number; growth_stage:string; company_type:string; main_pain:string; goal_90days:string; key_risks:string[]; competitive_advantages:string[]; recommended_ai_employee:string; diagnosis_date:string; answers?:number[]; is_demo?:boolean};

const rapQuestions = [
  ...["产品解决客户真实且紧迫的问题","客户愿意持续为产品或服务付款","性价比优于主要替代方案","我们非常清楚核心客户是谁","获客渠道稳定且可重复","销售转化机制有效","客户信任我们的企业与承诺","商业模式能够长期持续","收入来源相对稳定","客户有明显复购或推荐"].map((q,i)=>({d:"R",q,n:i+1})),
  ...["所在行业目前保持增长","市场空间足以支持未来增长","客户需求正在增加","竞争强度仍在可应对范围","行业存在技术、品牌、渠道或合规壁垒","企业掌握行业关键资源","行业利润空间健康","能够应对政策或技术变化","产品或服务可以规模化","企业在行业中的位置清晰"].map((q,i)=>({d:"A",q,n:i+1})),
  ...["创始团队具有扎实行业经验","团队拥有关键技术或知识","产品具有清晰差异化","企业拥有稳定客户资源","企业拥有有效销售渠道","团队执行能力足够","现金流可支持未来6个月","企业战略足够聚焦","组织和人才支持增长","企业已有效使用数据和AI","企业拥有难以复制的竞争优势"].map((q,i)=>({d:"P",q,n:i+1})),
];
const painAI:Record<string,string>={"客户不足":"AI销售线索与客户侦察助手","流量不足":"AI销售线索与客户侦察助手","销售转化低":"AI销售跟进与CRM助手","成本过高":"AI成本分析与流程自动化助手","团队执行问题":"AI任务追踪与CEO日报助手","行业竞争激烈":"AI市场情报助手","利润下降":"AI经营数据与现金流预警助手","现金流紧张":"AI经营数据与现金流预警助手","产品问题":"AI企业知识库与SOP助手","战略方向不清楚":"AI市场情报助手","AI转型不知道从哪里开始":"AI企业知识库与SOP助手"};
const demo:Profile={company_name:"湾区精密科技有限公司",location:"深圳",industry:"智能制造设备",employee_count:"35人",revenue_range:"示例范围",profit_margin:"示例范围",R:76,A:85,P:61,health_score:73,constraint_score:61,growth_stage:"初步规模化",company_type:"技术驱动型企业",main_pain:"销售转化低",goal_90days:"建立可重复销售流程",key_risks:["客户集中","销售周期过长","创始人依赖"],competitive_advantages:["行业经验","技术能力"],recommended_ai_employee:"AI销售线索与客户跟进助手",diagnosis_date:"2026-07-13",is_demo:true};

const score=(vals:number[])=>Math.round(((vals.reduce((a,b)=>a+b,0)-vals.length)/(vals.length*4))*100);
const band=(n:number)=>n>=80?"优势区":n>=60?"改善区":n>=40?"风险区":"警戒区";
const dimName:Record<string,string>={R:"商业共性",A:"行业特性",P:"企业个性"};

export default function Home(){
 const [view,setView]=useState<View>("home"),[step,setStep]=useState(0),[qPage,setQPage]=useState(0),[answers,setAnswers]=useState<number[]>(Array(31).fill(3)),[profile,setProfile]=useState<Profile|null>(null),[history,setHistory]=useState<Profile[]>([]),[demoMode,setDemoMode]=useState(false),[loading,setLoading]=useState(false),[msg,setMsg]=useState("");
 const [form,setForm]=useState({user_name:"",company_name:"",location:"深圳",business_type:"",customer_type:"企业客户",employee_count:"20-50人",revenue_monthly:"不方便提供",profit_margin:"不方便提供",company_age:"1-3年",sales_channel:"",main_pain:"客户不足",ai_usage:"尚未使用",goal_90days:"",compliance_risk:"暂无明显风险"});
 useEffect(()=>{fetch("/api/diagnoses").then(r=>r.ok?r.json():{records:[]}).then(x=>{setHistory(x.records||[]);if(x.records?.[0])setProfile(x.records[0])}).catch(()=>{})},[]);
 const active=demoMode?demo:profile;
 const go=(v:View)=>{setView(v);scrollTo({top:0,behavior:"smooth"})};
 const calculate=async()=>{setLoading(true);const R=score(answers.slice(0,10)),A=score(answers.slice(10,20)),P=score(answers.slice(20));const health=Math.round(.35*R+.30*A+.35*P);const low=Math.min(R,A,P), key=R===low?"R":A===low?"A":"P";let risks:string[]=[];if(R<60)risks.push("商业模式或客户价值风险");if(A<50)risks.push("行业环境或赛道选择风险");if(P<50)risks.push("团队、资源或执行能力风险");if(A>80&&P<60)risks.push("行业机会良好，但企业能力限制增长");if(form.profit_margin.includes("低")||form.main_pain==="利润下降")risks.push("增长质量与利润风险");if(form.main_pain==="现金流紧张")risks.unshift("现金流风险");risks=[...new Set(risks.concat([`${dimName[key]}是当前最低约束`]))].slice(0,3);const p:Profile={company_name:form.company_name||"未命名企业",location:form.location,industry:form.business_type||"未填写行业",employee_count:form.employee_count,revenue_range:form.revenue_monthly,profit_margin:form.profit_margin,R,A,P,health_score:health,constraint_score:low,growth_stage:health>=80?"加速增长":health>=60?"初步规模化":health>=40?"结构修复":"生存与重构",company_type:P>=R?"能力驱动型企业":"市场驱动型企业",main_pain:form.main_pain,goal_90days:form.goal_90days||"修复当前最大经营瓶颈",key_risks:risks,competitive_advantages:[R>=70?"客户价值基础":"行业经验",A>=70?"赛道机会":"团队韧性"],recommended_ai_employee:painAI[form.main_pain]||"AI企业知识库与SOP助手",diagnosis_date:new Date().toISOString().slice(0,10),answers};try{const res=await fetch("/api/diagnoses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)});const x=await res.json();const saved={...p,id:x.record?.id};setProfile(saved);setHistory(h=>[saved,...h]);setDemoMode(false);go("result")}catch{setMsg("暂时无法保存，请稍后重试。")}finally{setLoading(false)}};
 return <div className="app"><Header view={view} go={go}/>{demoMode&&<div className="demoBar">演示模式 · 这是示例数据，不代表真实企业诊断。<button onClick={()=>{setDemoMode(false);go("home")}}>退出演示</button></div>}
  {view==="home"&&<HomePage go={go} demo={()=>{setDemoMode(true);go("result")}}/>}
  {view==="checkup"&&<Checkup step={step} setStep={setStep} qPage={qPage} setQPage={setQPage} form={form} setForm={setForm} answers={answers} setAnswers={setAnswers} calculate={calculate} loading={loading} msg={msg}/>} 
  {view==="result"&&<Result p={active} go={go}/>} {view==="dashboard"&&<Dashboard p={active} history={demoMode?[demo]:history} go={go}/>} {view==="copilot"&&<Copilot p={active}/>} {view==="history"&&<History records={demoMode?[demo]:history} go={go}/>} {view==="about"&&<About/>}
  <footer><b>CSR-RAP Business Copilot v1.0</b><span>可解释企业诊断 · 不执行任何支付或金融交易</span></footer>
 </div>
}

function Header({view,go}:{view:View,go:(v:View)=>void}){return <header><button className="brand" onClick={()=>go("home")}><span>CR</span><div>CSR-RAP<small>AI商业副驾驶</small></div></button><nav>{[["home","首页"],["checkup","企业体检"],["dashboard","驾驶舱"],["copilot","AI副驾驶"],["history","历史记录"],["about","关于"]].map(([v,n])=><button className={view===v?"on":""} onClick={()=>go(v as View)} key={v}>{n}</button>)}</nav><button className="primary small" onClick={()=>go("checkup")}>免费体检</button></header>}
function HomePage({go,demo}:{go:(v:View)=>void,demo:()=>void}){return <main><section className="hero"><div className="eyebrow">CSR-RAP BUSINESS COPILOT · V1.0</div><h1>5分钟，看清企业<br/><em>真正的问题</em></h1><p>从商业共性、行业特性和企业个性三个维度建立经营画像，识别增长瓶颈，并生成可以立即执行的30／60／90天行动计划。</p><div className="actions"><button className="primary" onClick={()=>go("checkup")}>开始企业体检 <b>→</b></button><button className="secondary" onClick={demo}>先看示例报告</button><button className="textBtn" onClick={()=>go("copilot")}>直接咨询AI</button></div><div className="trust"><span>✓ 透明评分规则</span><span>✓ 数据最小化</span><span>✓ 不收集支付资料</span></div><div className="formula"><span>企业经营结果</span><strong>B = R × A × P</strong><div><i>R</i> 商业共性　<i>A</i> 行业特性　<i>P</i> 企业个性</div></div></section><section className="values">{[["01","看见问题","找出企业最重要的经营瓶颈，而不是只生成一份普通报告。"],["02","找到方向","判断市场是否值得做、企业能否赢，以及资源应该优先投入哪里。"],["03","立即行动","生成Top 3优先任务和30／60／90天行动计划。"]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><section className="flow"><div><div className="eyebrow">从填写到行动</div><h2>不止是一份问卷报告</h2><p>传统企业体检往往停留在“填写问卷—生成报告”。CSR-RAP把信息转化为可追踪的经营决策。</p></div><div className="flowline">{["企业数据","R/A/P商业诊断","企业数字画像","风险与机会识别","最优行动建议"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div></section><section className="cta"><h2>现在开始，为企业建立第一张经营画像</h2><p>约5分钟完成 · 可随时返回修改 · 结果自动保存</p><button className="primary" onClick={()=>go("checkup")}>开始免费体检 →</button></section></main>}

function Checkup({step,setStep,qPage,setQPage,form,setForm,answers,setAnswers,calculate,loading,msg}:any){const phases=["企业资料","当前痛点","R商业共性","A行业特性","P企业个性","生成结果"];const fields=step===0?[["user_name","姓名或称呼"],["company_name","企业名称"],["location","地区"],["business_type","所属行业"],["customer_type","主要客户类型"],["employee_count","员工人数"],["revenue_monthly","大致月营业额"],["profit_margin","大致利润率"],["company_age","成立时间"],["sales_channel","主要销售渠道"]]:[["ai_usage","目前如何使用AI"],["goal_90days","未来90天最想实现的目标"],["compliance_risk","主要合规或经营风险"]];const pain=["产品问题","客户不足","流量不足","销售转化低","利润下降","成本过高","现金流紧张","团队执行问题","行业竞争激烈","战略方向不清楚","AI转型不知道从哪里开始","其他问题"];
 const qs=step>=2&&step<=4?rapQuestions.filter(x=>x.d===["R","A","P"][step-2]):[];const pages=Math.ceil(qs.length/3),shown=qs.slice(qPage*3,qPage*3+3);const next=()=>{if(step<2){setStep(step+1);setQPage(0)}else if(qPage<pages-1)setQPage(qPage+1);else{setStep(step+1);setQPage(0)}};const back=()=>{if(step>=2&&qPage>0)setQPage(qPage-1);else{setStep(Math.max(0,step-1));setQPage(0)}};
 return <main className="check"><div className="progress">{phases.map((x,i)=><span className={i<=step?"active":""} key={x}><i>{i<step?"✓":i+1}</i>{x}</span>)}</div><section className="formCard"><div className="stepTag">步骤 {step+1} / 6</div><h2>{step===0?"先了解您的企业":step===1?"现在最需要解决什么？":step<5?`${["R · 商业共性","A · 行业特性","P · 企业个性"][step-2]}诊断`:"准备生成诊断"}</h2><p className="muted">{step<2?"这些信息用于建立企业画像；不方便提供的经营数据可以跳过。":"请根据企业当前真实情况作答，没有标准答案。"}</p>
 {step<2&&<>{step===1&&<div><label>当前最重要的经营痛点</label><div className="painGrid">{pain.map((x:string)=><button className={form.main_pain===x?"selected":""} onClick={()=>setForm({...form,main_pain:x})} key={x}>{x}</button>)}</div></div>}<div className="fieldGrid">{fields.map(([k,l]:string[])=><label key={k}>{l}<input value={form[k]} placeholder={`请输入${l}`} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div></>}
 {step>=2&&step<=4&&<div className="questions">{shown.map((x:any)=>{const idx=rapQuestions.indexOf(x);return <div className="question" key={x.q}><b>{x.d}{x.n}. {x.q}</b><div>{[1,2,3,4,5].map(n=><button className={answers[idx]===n?"chosen":""} onClick={()=>{const a=[...answers];a[idx]=n;setAnswers(a)}} key={n}><strong>{n}</strong><small>{["完全不符合","较不符合","一般／不确定","比较符合","非常符合"][n-1]}</small></button>)}</div></div>})}<p className="pageNo">本维度第 {qPage+1} / {pages} 页 · 每页最多3题</p></div>}
 {step===5&&<div className="privacy"><b>提交前请确认</b><p>您提供的信息将用于生成企业诊断结果。请勿上传商业秘密、银行卡资料、身份证号码、医疗资料或其他不必要的敏感信息。</p><label><input type="checkbox" defaultChecked/> 我已阅读并同意以上说明</label></div>}
 {msg&&<p className="error">{msg}</p>}<div className="formNav">{step>0&&<button className="secondary" onClick={back}>← 返回修改</button>}<button className="primary" onClick={step===5?calculate:next} disabled={loading}>{loading?"正在生成…":step===5?"生成CSR-RAP诊断":"继续 →"}</button></div></section></main>}

function Result({p,go}:{p:Profile|null,go:(v:View)=>void}){if(!p)return <Empty go={go}/>;const low=p.R===p.constraint_score?"R":p.A===p.constraint_score?"A":"P";const judgment=p.A>=80&&p.P<65?"您的行业仍有增长机会，但当前主要约束不是市场，而是企业执行能力。":p.R<60?"当前最优先任务是验证客户价值与商业模式，而不是盲目扩张。":p.health_score>=80?"企业基础较强，适合扩大优势并建立更高竞争壁垒。":`企业基本条件成立，但${dimName[low]}正在限制下一阶段增长。`;return <main className="report"><div className="reportHead"><div><div className="eyebrow">CSR-RAP 企业诊断报告</div><h1>{p.company_name}</h1><p>{p.diagnosis_date} · {p.growth_stage} · {p.company_type}</p><blockquote>{judgment}</blockquote></div><ScoreRing n={p.health_score}/></div><DemoNote p={p}/><section className="scoreGrid">{[["R",p.R],["A",p.A],["P",p.P]].map(([d,n]:any)=><article key={d}><span>{d} · {dimName[d]}</span><strong>{n}</strong><div><i style={{width:n+"%"}}/></div><small>{band(n)}</small></article>)}</section><div className="constraint"><span>当前最大约束</span><b>{low} · {dimName[low]}（{p.constraint_score}分）</b><p>整体能力会受到最低维度约束，应优先修复该短板。</p></div><section className="twoCol"><article><h2>Top 3 经营风险</h2>{p.key_risks.map((x,i)=><p className="listItem" key={x}><b>{i+1}</b>{x}</p>)}</article><article><h2>Top 3 优先行动</h2>{actions(p).map((x,i)=><p className="listItem green" key={x}><b>{i+1}</b>{x}</p>)}</article></section><AIEmployee p={p}/><Plan p={p}/><p className="disclaimer">本诊断基于用户提供的信息和CSR-RAP规则引擎生成，仅供经营分析与决策参考，不构成法律、审计、税务、投资、融资或财务建议，也不保证特定经营结果。评分来源：31道R/A/P结构化题；健康指数 = 0.35R + 0.30A + 0.35P；约束分 = min(R,A,P)。</p><div className="center"><button className="primary" onClick={()=>go("dashboard")}>进入老板驾驶舱 →</button><button className="secondary" onClick={()=>go("checkup")}>重新诊断</button></div></main>}
function ScoreRing({n}:{n:number}){return <div className="scoreRing" style={{background:`conic-gradient(#19a58c ${n*3.6}deg,#dce8e8 0)`}}><div><strong>{n}</strong><span>企业健康指数</span><small>{band(n)}</small></div></div>}
function actions(p:Profile){return p.main_pain==="现金流紧张"?["建立13周滚动现金流表并每日检查","暂停非核心支出，确认应收账款负责人","与Top客户确认回款节点"]:[`优先修复${dimName[p.R===p.constraint_score?"R":p.A===p.constraint_score?"A":"P"]}最低约束`,`为“${p.goal_90days}”设定每周指标`,`7天内启动${p.recommended_ai_employee}试点`];}
function AIEmployee({p}:{p:Profile}){return <section className="aiBox"><div><span>推荐的第一个AI员工</span><h2>{p.recommended_ai_employee}</h2><p>聚焦解决“{p.main_pain}”，连接现有客户、销售或业务流程数据；先做小范围、可衡量的7天试点。</p></div><div><b>7天第一步</b><p>整理最近30天相关记录，选择一个重复、高频、低风险流程进行测试。</p><small>观察指标：节省时间、任务完成率、有效线索或响应速度</small></div></section>}
function Plan({p}:{p:Profile}){return <section><div className="sectionHead"><span>行动路线图</span><h2>30／60／90天计划</h2></div><div className="plan">{[["30天","修复最紧急问题",actions(p)[0],"最低约束改善5分"],["60天","建立可重复流程",`围绕${p.main_pain}建立负责人、SOP和周报`,"流程执行率≥80%"],["90天","验证增长",`复盘${p.goal_90days}及收入、利润、客户指标`,"完成再次诊断"]].map((x,i)=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p><b>行动：</b>{x[2]}</p><p><b>负责人：</b>{i===0?"创始人／CEO":"业务负责人"}</p><small>成功指标：{x[3]} · 建议复盘：{i===0?"第30天":i===1?"第60天":"第90天"}</small></article>)}</div></section>}

function Dashboard({p,history,go}:{p:Profile|null,history:Profile[],go:(v:View)=>void}){if(!p)return <Empty go={go}/>;const low=p.R===p.constraint_score?"R":p.A===p.constraint_score?"A":"P";return <main className="dash"><div className="dashTitle"><div><div className="eyebrow">CSR-RAP BUSINESS DASHBOARD</div><h1>老板驾驶舱</h1><p>{p.company_name} · 最近诊断 {p.diagnosis_date}</p></div><button className="secondary" onClick={()=>go("checkup")}>再次诊断</button></div><DemoNote p={p}/><section className="metrics"><article><span>企业健康指数</span><strong>{p.health_score}</strong><small>{history.length>1?"趋势：与上次比较":"暂无真实趋势数据"}</small></article>{[["R",p.R],["A",p.A],["P",p.P]].map(([x,n])=><article key={x}><span>{x} · {dimName[x as string]}</span><strong>{n}</strong><small>{band(n as number)}</small></article>)}</section><section className="dashGrid"><article className="constraintPanel"><span>当前最大约束</span><h2>{low} · {dimName[low]}</h2><strong>{p.constraint_score}分</strong><p>优先修复短板，再扩大投入。</p></article><article><h2>今日风险</h2>{p.key_risks.map(x=><p className="risk" key={x}>!　{x}</p>)}</article><article className="advice"><h2>AI建议</h2>{actions(p).map(x=><p key={x}>✓　{x}</p>)}</article></section><section className="goal"><div><span>当前90天目标</span><h2>{p.goal_90days}</h2></div><div><strong>1</strong><span>已完成行动</span></div><div><strong>5</strong><span>待完成行动</span></div><button className="primary" onClick={()=>go("copilot")}>咨询AI副驾驶</button></section><Plan p={p}/></main>}
function Copilot({p}:{p:Profile|null}){const [chat,setChat]=useState<{who:string,text:string}[]>([]),[input,setInput]=useState("");const qs=["为什么最近利润下降？","我应该先增加销售还是降低成本？","我的最大增长瓶颈是什么？","我们适合部署哪个AI员工？","如何实现未来90天目标？","我现在适合扩张吗？"];const ask=(q:string)=>{if(!q)return;let text=p?`核心判断：${p.R===p.constraint_score?"客户价值与商业模式":p.A===p.constraint_score?"行业环境与赛道":"团队资源与执行"}是当前主要约束。\n\nCSR-RAP依据：R ${p.R}、A ${p.A}、P ${p.P}；最低约束为${p.constraint_score}分。\n\n建议行动：\n1. ${actions(p)[0]}\n2. ${actions(p)[1]}\n3. ${actions(p)[2]}\n\n追踪指标：7天任务完成率、30天关键经营指标、最低维度变化。`:`核心判断：目前没有企业画像，无法给出可靠判断。\n\n请先完成企业体检，或告诉我您的行业、最重要的经营问题和未来90天目标。`;setChat(c=>[...c,{who:"您",text:q},{who:"AI副驾驶",text}]);setInput("")};return <main className="copilot"><div className="copilotIntro"><div className="bot">CR</div><h1>CSR-RAP AI商业副驾驶</h1><p>您好，我不是通用聊天机器人。我会根据您的企业画像、R/A/P评分、主要目标和经营风险，帮助您分析问题并提出可执行建议。您今天最想解决哪个经营问题？</p></div>{p&&<div className="context">已读取企业画像：{p.company_name} · R {p.R} / A {p.A} / P {p.P}</div>}<div className="quick">{qs.map(q=><button onClick={()=>ask(q)} key={q}>{q}</button>)}</div><div className="chat">{chat.length===0?<div className="emptyChat">选择上方问题，或在下方输入您的经营问题。</div>:chat.map((x,i)=><div className={x.who==="您"?"userMsg":"aiMsg"} key={i}><b>{x.who}</b><p>{x.text}</p></div>)}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask(input)} placeholder="请输入一个具体经营问题…"/><button className="primary" onClick={()=>ask(input)}>发送</button></div><p className="disclaimer">AI回答仅供经营决策参考，财务、法律、税务和投资事项不能替代持牌专业意见。</p></main>}
function History({records,go}:{records:Profile[],go:(v:View)=>void}){return <main className="history"><div className="eyebrow">持续学习</div><h1>历史诊断记录</h1><p>比较历次结构化企业画像，观察真实变化。示例数据、真实数据和AI推断始终明确区分。</p>{records.length===0?<Empty go={go}/>:<div className="tableWrap"><table><thead><tr><th>数据类型／日期</th><th>企业</th><th>R</th><th>A</th><th>P</th><th>健康指数</th><th>最大约束</th><th>90天目标</th></tr></thead><tbody>{records.map((p,i)=><tr key={p.id||i}><td><span className={p.is_demo?"sample":"real"}>{p.is_demo?"示例数据":"当前真实数据"}</span><br/>{p.diagnosis_date}</td><td>{p.company_name}</td><td>{p.R}</td><td>{p.A}</td><td>{p.P}</td><td><b>{p.health_score}</b></td><td>{p.constraint_score}</td><td>{p.goal_90days}</td></tr>)}</tbody></table>{records.length<2&&<div className="emptyTrend">完成第二次真实诊断后，这里将显示评分趋势图。目前不伪造趋势。</div>}</div>}</main>}
function About(){return <main className="about"><div className="eyebrow">ABOUT CSR-RAP</div><h1>把复杂经营问题，转化为可解释的行动</h1><p className="lead">商业三性认为，企业经营结果来自三个方面的共同作用。</p><section className="rapCards">{[["R","商业共性 Regularity","所有商业都必须遵守的共同规律：真实价值、需求、性价比、模式、获客与信任。"],["A","行业特性 Application / Industry","不同行业的特殊规律：增长、市场、竞争、壁垒、政策风险和规模化潜力。"],["P","企业个性 Personality","每家企业独有的能力、资源和限制：团队、产品、渠道、执行、聚焦与优势。"]].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</section><section className="definition"><h2>CSR在这里是什么意思？</h2><p><b>CSR在本网站中特指复杂系统CSR理论及其商业应用，不是Corporate Social Responsibility（企业社会责任）。</b></p><p>CSR-RAP将企业视为一个持续变化的复杂系统。第一代MVP先使用透明、可解释的规则引擎，把企业数据转换成经营诊断和行动建议；未来才逐步增加动态预测、情境模拟和商业方程。</p></section><section className="consult"><h2>申请CSR-RAP专业咨询</h2><p>如需进一步分析，请留下基本联系信息。我们不会收集银行卡、信用卡或支付密码。</p><ConsultForm/></section></main>}
function ConsultForm(){const [ok,setOk]=useState(false);if(ok)return <div className="success">✓ 您的申请已经提交。CSR-RAP团队将根据您提供的信息与您联系。</div>;return <form className="consultForm" onSubmit={e=>{e.preventDefault();setOk(true)}}>{["姓名","企业名称","联系方式","所在地区","希望解决的问题","希望联系时间"].map(x=><label key={x}>{x}<input required placeholder={`请输入${x}`}/></label>)}<label className="agree"><input required type="checkbox"/> 我同意隐私声明</label><button className="primary">提交咨询申请</button></form>}
function Empty({go}:{go:(v:View)=>void}){return <section className="empty"><div>⌁</div><h2>还没有企业诊断数据</h2><p>请先完成一次企业体检，系统才会建立企业画像与驾驶舱。</p><button className="primary" onClick={()=>go("checkup")}>开始企业体检</button></section>}
function DemoNote({p}:{p:Profile}){return p.is_demo?<div className="demoNote"><b>示例数据</b> 这是示例企业演示，不代表真实企业诊断，也不会覆盖您的真实数据。</div>:null}
